# Generated by Django 4.1.2 on 2022-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
